# Generated by Django 6.1 on 2026-08-21 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attachments", "0003_initial"),
        ("companies", "0002_initial"),
        ("contracts", "0001_initial"),
        ("customers", "0001_initial"),
        ("elevators", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="previous_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="renewals",
                to="contracts.contract",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="attachments.attachment",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractelevator",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="contractelevator",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="contracts.contract",
            ),
        ),
        migrations.AddField(
            model_name="contractelevator",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractelevator",
            name="elevator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_lines",
                to="elevators.elevator",
            ),
        ),
        migrations.AddField(
            model_name="contractelevator",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("company", "contract_number"),
                name="uq_contract_number_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "active", "expired", "terminated", "renewed"])
                ),
                name="contract_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="contract_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "terminated"), _negated=True),
                    ("terminated_at__isnull", False),
                    _connector="OR",
                ),
                name="contract_terminated_requires_date",
            ),
        ),
        migrations.AddIndex(
            model_name="contractelevator",
            index=models.Index(
                fields=["contract", "removed_at"], name="contract_el_contrac_aa20af_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractelevator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("removed_at__isnull", True)),
                fields=("elevator",),
                name="uq_elevator_active_contract",
            ),
        ),
    ]
