# Generated by Django 6.1 on 2026-08-21 21:37

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("auditor", "Auditor"),
                            ("caretaker", "Caretaker"),
                            ("technical_lead", "Technical lead"),
                            ("accounting", "Accounting"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=150)),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "customer_contact",
                "ordering": ["-is_primary", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("complex_management", "Complex management"),
                            ("building_management", "Building management"),
                            ("corporate", "Corporate"),
                            ("public", "Public"),
                            ("individual", "Individual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("tax_office", models.CharField(blank=True, max_length=100)),
                ("tax_number", models.CharField(blank=True, max_length=11)),
                ("national_id", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=150)),
                ("street", models.CharField(blank=True, max_length=150)),
                ("building_number", models.CharField(blank=True, max_length=20)),
                ("unit_number", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "customer",
                "ordering": ["legal_name"],
            },
        ),
    ]
