# Generated by Django 6.1 on 2026-08-21 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0001_initial"),
        ("companies", "0002_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="address.neighborhood",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customercontact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="customercontact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customercontact",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="customercontact",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "complex_management",
                            "building_management",
                            "corporate",
                            "public",
                            "individual",
                        ],
                    )
                ),
                name="customer_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="customercontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        [
                            "manager",
                            "auditor",
                            "caretaker",
                            "technical_lead",
                            "accounting",
                            "other",
                        ],
                    )
                ),
                name="customer_contact_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="customercontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("is_primary", True)),
                fields=("customer",),
                name="uq_customer_primary_contact",
            ),
        ),
    ]
