# Generated by Django 6.1 on 2026-08-21 21:37

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("registration_number", models.CharField(blank=True, max_length=30)),
                ("internal_code", models.CharField(blank=True, max_length=30)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("qr_token", models.CharField(max_length=24, unique=True)),
                ("qr_token_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passenger", "Passenger"),
                            ("freight", "Freight"),
                            ("passenger_freight", "Passenger and freight"),
                            ("dumbwaiter", "Dumbwaiter"),
                            ("accessibility_platform", "Accessibility platform"),
                            ("vehicle", "Vehicle"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("geared_electric", "Geared electric"),
                            ("gearless_electric", "Gearless electric"),
                            ("hydraulic", "Hydraulic"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple_collective", "Simple collective"),
                            ("down_collective", "Down collective"),
                            ("full_collective", "Full collective"),
                            ("group_control", "Group control"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "door_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("automatic_center", "Automatic centre opening"),
                            ("automatic_side", "Automatic side opening"),
                            ("semi_automatic", "Semi automatic"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("has_car_door", models.BooleanField(blank=True, null=True)),
                (
                    "machine_room",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("partial", "Partial"),
                        ],
                        max_length=16,
                    ),
                ),
                ("capacity_kg", models.IntegerField(blank=True, null=True)),
                ("capacity_persons", models.SmallIntegerField(blank=True, null=True)),
                ("stop_count", models.SmallIntegerField(blank=True, null=True)),
                ("entrance_count", models.SmallIntegerField(blank=True, null=True)),
                (
                    "speed_mps",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("pit_depth_mm", models.IntegerField(blank=True, null=True)),
                ("headroom_mm", models.IntegerField(blank=True, null=True)),
                ("car_weight_kg", models.IntegerField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                ("installer", models.CharField(blank=True, max_length=150)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("commissioning_date", models.DateField(blank=True, null=True)),
                ("ce_certificate_number", models.CharField(blank=True, max_length=60)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                (
                    "inspection_label",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("next_inspection_date", models.DateField(blank=True, null=True)),
                ("inspection_body", models.CharField(blank=True, max_length=150)),
                ("inspection_report_number", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("sealed", "Sealed"),
                            ("out_of_service", "Out of service"),
                            ("uncontracted", "Uncontracted"),
                        ],
                        default="uncontracted",
                        max_length=32,
                    ),
                ),
                ("maintenance_interval_days", models.SmallIntegerField(default=30)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "elevator",
                "ordering": ["name"],
            },
        ),
    ]
