# Generated by Django 6.1 on 2026-08-21 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("elevators", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="elevator",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="elevator",
            index=models.Index(fields=["company", "status"], name="elevator_company_0304a1_idx"),
        ),
        migrations.AddIndex(
            model_name="elevator",
            index=models.Index(fields=["building"], name="elevator_buildin_055c4b_idx"),
        ),
        migrations.AddIndex(
            model_name="elevator",
            index=models.Index(fields=["next_inspection_date"], name="elevator_next_in_4433a2_idx"),
        ),
        migrations.AddConstraint(
            model_name="elevator",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), models.Q(("registration_number", ""), _negated=True)
                ),
                fields=("company", "registration_number"),
                name="uq_elevator_registration_number_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="elevator",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["active", "suspended", "sealed", "out_of_service", "uncontracted"],
                    )
                ),
                name="elevator_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="elevator",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maintenance_interval_days__gte", 1), ("maintenance_interval_days__lte", 30)
                ),
                name="elevator_maintenance_interval_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="elevator",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity_kg__isnull", True), ("capacity_kg__gt", 0), _connector="OR"
                ),
                name="elevator_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="elevator",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stop_count__isnull", True),
                    models.Q(("stop_count__gte", 2), ("stop_count__lte", 100)),
                    _connector="OR",
                ),
                name="elevator_stop_count_range",
            ),
        ),
    ]
