# Generated by Django 6.1 on 2026-08-21 21:37

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("legal_name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=80)),
                ("tax_office", models.CharField(blank=True, max_length=100)),
                ("tax_number", models.CharField(blank=True, max_length=11)),
                ("mersis_number", models.CharField(blank=True, max_length=16)),
                ("trade_registry_number", models.CharField(blank=True, max_length=30)),
                ("street", models.CharField(blank=True, max_length=150)),
                ("building_number", models.CharField(blank=True, max_length=20)),
                ("unit_number", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=150)),
                ("website", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "db_table": "company",
                "ordering": ["display_name"],
            },
        ),
    ]
