# Generated by Django 6.1 on 2026-08-21 21:37

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("elevator", "Elevator"),
                            ("building", "Building"),
                            ("contract", "Contract"),
                            ("customer", "Customer"),
                            ("company", "Company"),
                            ("user", "User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("ce_certificate", "CE certificate"),
                            ("declaration_of_conformity", "Declaration of conformity"),
                            ("permit", "Permit"),
                            ("signed_contract", "Signed contract"),
                            ("inspection_report", "Inspection report"),
                            ("logo", "Logo"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.IntegerField()),
                ("storage_key", models.CharField(max_length=500)),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("r2", "Cloudflare R2"),
                            ("local", "Local (development)"),
                            ("tr_provider", "Turkey-resident provider"),
                        ],
                        default="r2",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "attachment",
                "ordering": ["-created_at"],
            },
        ),
    ]
