# Generated by Django 6.1 on 2026-08-21 21:37

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("street", models.CharField(blank=True, max_length=150)),
                ("building_number", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "complexes",
                "db_table": "complex",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed_use", "Mixed use"),
                            ("public", "Public"),
                            ("hospital", "Hospital"),
                            ("mall", "Mall"),
                            ("hotel", "Hotel"),
                            ("school", "School"),
                            ("industrial", "Industrial"),
                        ],
                        max_length=32,
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=150)),
                ("building_number", models.CharField(blank=True, max_length=20)),
                ("address_note", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("floor_count", models.SmallIntegerField(blank=True, null=True)),
                ("unit_count", models.SmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "building",
                "ordering": ["name"],
            },
        ),
    ]
