# Generated by Django 6.1 on 2026-08-21 21:43

from django.db import migrations

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
