# Generated by Django 6.1 on 2026-08-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("name_normalized", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "db_table": "province",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("name_normalized", models.CharField(db_index=True, max_length=80)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="districts",
                        to="address.province",
                    ),
                ),
            ],
            options={
                "db_table": "district",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("name_normalized", models.CharField(max_length=120)),
                ("postal_code", models.CharField(blank=True, db_index=True, max_length=5)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("neighborhood", "Neighborhood"),
                            ("village", "Village"),
                            ("town", "Town"),
                        ],
                        default="neighborhood",
                        max_length=20,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="neighborhoods",
                        to="address.district",
                    ),
                ),
            ],
            options={
                "db_table": "neighborhood",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["district"], name="neighborhoo_distric_1e2400_idx"),
                    models.Index(fields=["name_normalized"], name="neighborhood_name_norm_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("type__in", ["neighborhood", "village", "town"])),
                        name="neighborhood_type_valid",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                fields=["province", "name_normalized"], name="district_provinc_b343f5_idx"
            ),
        ),
    ]
