# Generated by Django 6.1 on 2026-08-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("company_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("table_name", models.CharField(max_length=60)),
                ("record_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        max_length=10,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_id", "-created_at"], name="audit_log_company_5ffdd8_idx"
                    ),
                    models.Index(
                        fields=["table_name", "record_id"], name="audit_log_table_n_38ccfb_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("action__in", ["create", "update", "delete"])),
                        name="audit_log_action_valid",
                    )
                ],
            },
        ),
    ]
